// Generated by gencpp from file wam_msgs/MatrixMN.msg
// DO NOT EDIT!


#ifndef WAM_MSGS_MESSAGE_MATRIXMN_H
#define WAM_MSGS_MESSAGE_MATRIXMN_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace wam_msgs
{
template <class ContainerAllocator>
struct MatrixMN_
{
  typedef MatrixMN_<ContainerAllocator> Type;

  MatrixMN_()
    : m(0)
    , n(0)
    , data()  {
    }
  MatrixMN_(const ContainerAllocator& _alloc)
    : m(0)
    , n(0)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _m_type;
  _m_type m;

   typedef int32_t _n_type;
  _n_type n;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::wam_msgs::MatrixMN_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wam_msgs::MatrixMN_<ContainerAllocator> const> ConstPtr;

}; // struct MatrixMN_

typedef ::wam_msgs::MatrixMN_<std::allocator<void> > MatrixMN;

typedef boost::shared_ptr< ::wam_msgs::MatrixMN > MatrixMNPtr;
typedef boost::shared_ptr< ::wam_msgs::MatrixMN const> MatrixMNConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::wam_msgs::MatrixMN_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::wam_msgs::MatrixMN_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace wam_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'wam_msgs': ['/home/dhruv/RobotArm/wam_dir/src/wam_common/wam_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::wam_msgs::MatrixMN_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wam_msgs::MatrixMN_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wam_msgs::MatrixMN_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wam_msgs::MatrixMN_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wam_msgs::MatrixMN_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wam_msgs::MatrixMN_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::wam_msgs::MatrixMN_<ContainerAllocator> >
{
  static const char* value()
  {
    return "28e4f87d99ae219cf43e9311a87d6fce";
  }

  static const char* value(const ::wam_msgs::MatrixMN_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x28e4f87d99ae219cULL;
  static const uint64_t static_value2 = 0xf43e9311a87d6fceULL;
};

template<class ContainerAllocator>
struct DataType< ::wam_msgs::MatrixMN_<ContainerAllocator> >
{
  static const char* value()
  {
    return "wam_msgs/MatrixMN";
  }

  static const char* value(const ::wam_msgs::MatrixMN_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::wam_msgs::MatrixMN_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Matrix m x n stored in column order inside of data\n\
int32 m  #rows\n\
int32 n  #columns\n\
float64[] data\n\
";
  }

  static const char* value(const ::wam_msgs::MatrixMN_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::wam_msgs::MatrixMN_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.m);
      stream.next(m.n);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MatrixMN_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::wam_msgs::MatrixMN_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::wam_msgs::MatrixMN_<ContainerAllocator>& v)
  {
    s << indent << "m: ";
    Printer<int32_t>::stream(s, indent + "  ", v.m);
    s << indent << "n: ";
    Printer<int32_t>::stream(s, indent + "  ", v.n);
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // WAM_MSGS_MESSAGE_MATRIXMN_H
