// Generated by gencpp from file wam_srvs/BHandSpreadPos.msg
// DO NOT EDIT!


#ifndef WAM_SRVS_MESSAGE_BHANDSPREADPOS_H
#define WAM_SRVS_MESSAGE_BHANDSPREADPOS_H

#include <ros/service_traits.h>


#include <wam_srvs/BHandSpreadPosRequest.h>
#include <wam_srvs/BHandSpreadPosResponse.h>


namespace wam_srvs
{

struct BHandSpreadPos
{

typedef BHandSpreadPosRequest Request;
typedef BHandSpreadPosResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct BHandSpreadPos
} // namespace wam_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::wam_srvs::BHandSpreadPos > {
  static const char* value()
  {
    return "718158cfca4f89c6952f799c53697f42";
  }

  static const char* value(const ::wam_srvs::BHandSpreadPos&) { return value(); }
};

template<>
struct DataType< ::wam_srvs::BHandSpreadPos > {
  static const char* value()
  {
    return "wam_srvs/BHandSpreadPos";
  }

  static const char* value(const ::wam_srvs::BHandSpreadPos&) { return value(); }
};


// service_traits::MD5Sum< ::wam_srvs::BHandSpreadPosRequest> should match 
// service_traits::MD5Sum< ::wam_srvs::BHandSpreadPos > 
template<>
struct MD5Sum< ::wam_srvs::BHandSpreadPosRequest>
{
  static const char* value()
  {
    return MD5Sum< ::wam_srvs::BHandSpreadPos >::value();
  }
  static const char* value(const ::wam_srvs::BHandSpreadPosRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_srvs::BHandSpreadPosRequest> should match 
// service_traits::DataType< ::wam_srvs::BHandSpreadPos > 
template<>
struct DataType< ::wam_srvs::BHandSpreadPosRequest>
{
  static const char* value()
  {
    return DataType< ::wam_srvs::BHandSpreadPos >::value();
  }
  static const char* value(const ::wam_srvs::BHandSpreadPosRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::wam_srvs::BHandSpreadPosResponse> should match 
// service_traits::MD5Sum< ::wam_srvs::BHandSpreadPos > 
template<>
struct MD5Sum< ::wam_srvs::BHandSpreadPosResponse>
{
  static const char* value()
  {
    return MD5Sum< ::wam_srvs::BHandSpreadPos >::value();
  }
  static const char* value(const ::wam_srvs::BHandSpreadPosResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_srvs::BHandSpreadPosResponse> should match 
// service_traits::DataType< ::wam_srvs::BHandSpreadPos > 
template<>
struct DataType< ::wam_srvs::BHandSpreadPosResponse>
{
  static const char* value()
  {
    return DataType< ::wam_srvs::BHandSpreadPos >::value();
  }
  static const char* value(const ::wam_srvs::BHandSpreadPosResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WAM_SRVS_MESSAGE_BHANDSPREADPOS_H
