// Generated by gencpp from file wam_srvs/BHandPinchPos.msg
// DO NOT EDIT!


#ifndef WAM_SRVS_MESSAGE_BHANDPINCHPOS_H
#define WAM_SRVS_MESSAGE_BHANDPINCHPOS_H

#include <ros/service_traits.h>


#include <wam_srvs/BHandPinchPosRequest.h>
#include <wam_srvs/BHandPinchPosResponse.h>


namespace wam_srvs
{

struct BHandPinchPos
{

typedef BHandPinchPosRequest Request;
typedef BHandPinchPosResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct BHandPinchPos
} // namespace wam_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::wam_srvs::BHandPinchPos > {
  static const char* value()
  {
    return "718158cfca4f89c6952f799c53697f42";
  }

  static const char* value(const ::wam_srvs::BHandPinchPos&) { return value(); }
};

template<>
struct DataType< ::wam_srvs::BHandPinchPos > {
  static const char* value()
  {
    return "wam_srvs/BHandPinchPos";
  }

  static const char* value(const ::wam_srvs::BHandPinchPos&) { return value(); }
};


// service_traits::MD5Sum< ::wam_srvs::BHandPinchPosRequest> should match 
// service_traits::MD5Sum< ::wam_srvs::BHandPinchPos > 
template<>
struct MD5Sum< ::wam_srvs::BHandPinchPosRequest>
{
  static const char* value()
  {
    return MD5Sum< ::wam_srvs::BHandPinchPos >::value();
  }
  static const char* value(const ::wam_srvs::BHandPinchPosRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_srvs::BHandPinchPosRequest> should match 
// service_traits::DataType< ::wam_srvs::BHandPinchPos > 
template<>
struct DataType< ::wam_srvs::BHandPinchPosRequest>
{
  static const char* value()
  {
    return DataType< ::wam_srvs::BHandPinchPos >::value();
  }
  static const char* value(const ::wam_srvs::BHandPinchPosRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::wam_srvs::BHandPinchPosResponse> should match 
// service_traits::MD5Sum< ::wam_srvs::BHandPinchPos > 
template<>
struct MD5Sum< ::wam_srvs::BHandPinchPosResponse>
{
  static const char* value()
  {
    return MD5Sum< ::wam_srvs::BHandPinchPos >::value();
  }
  static const char* value(const ::wam_srvs::BHandPinchPosResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_srvs::BHandPinchPosResponse> should match 
// service_traits::DataType< ::wam_srvs::BHandPinchPos > 
template<>
struct DataType< ::wam_srvs::BHandPinchPosResponse>
{
  static const char* value()
  {
    return DataType< ::wam_srvs::BHandPinchPos >::value();
  }
  static const char* value(const ::wam_srvs::BHandPinchPosResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WAM_SRVS_MESSAGE_BHANDPINCHPOS_H
