// Generated by gencpp from file wam_srvs/CartPosMove.msg
// DO NOT EDIT!


#ifndef WAM_SRVS_MESSAGE_CARTPOSMOVE_H
#define WAM_SRVS_MESSAGE_CARTPOSMOVE_H

#include <ros/service_traits.h>


#include <wam_srvs/CartPosMoveRequest.h>
#include <wam_srvs/CartPosMoveResponse.h>


namespace wam_srvs
{

struct CartPosMove
{

typedef CartPosMoveRequest Request;
typedef CartPosMoveResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CartPosMove
} // namespace wam_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::wam_srvs::CartPosMove > {
  static const char* value()
  {
    return "993d3a0cca92114d34b338aeb1007ee4";
  }

  static const char* value(const ::wam_srvs::CartPosMove&) { return value(); }
};

template<>
struct DataType< ::wam_srvs::CartPosMove > {
  static const char* value()
  {
    return "wam_srvs/CartPosMove";
  }

  static const char* value(const ::wam_srvs::CartPosMove&) { return value(); }
};


// service_traits::MD5Sum< ::wam_srvs::CartPosMoveRequest> should match 
// service_traits::MD5Sum< ::wam_srvs::CartPosMove > 
template<>
struct MD5Sum< ::wam_srvs::CartPosMoveRequest>
{
  static const char* value()
  {
    return MD5Sum< ::wam_srvs::CartPosMove >::value();
  }
  static const char* value(const ::wam_srvs::CartPosMoveRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_srvs::CartPosMoveRequest> should match 
// service_traits::DataType< ::wam_srvs::CartPosMove > 
template<>
struct DataType< ::wam_srvs::CartPosMoveRequest>
{
  static const char* value()
  {
    return DataType< ::wam_srvs::CartPosMove >::value();
  }
  static const char* value(const ::wam_srvs::CartPosMoveRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::wam_srvs::CartPosMoveResponse> should match 
// service_traits::MD5Sum< ::wam_srvs::CartPosMove > 
template<>
struct MD5Sum< ::wam_srvs::CartPosMoveResponse>
{
  static const char* value()
  {
    return MD5Sum< ::wam_srvs::CartPosMove >::value();
  }
  static const char* value(const ::wam_srvs::CartPosMoveResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_srvs::CartPosMoveResponse> should match 
// service_traits::DataType< ::wam_srvs::CartPosMove > 
template<>
struct DataType< ::wam_srvs::CartPosMoveResponse>
{
  static const char* value()
  {
    return DataType< ::wam_srvs::CartPosMove >::value();
  }
  static const char* value(const ::wam_srvs::CartPosMoveResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WAM_SRVS_MESSAGE_CARTPOSMOVE_H
