// Generated by gencpp from file wam_srvs/CartVel.msg
// DO NOT EDIT!


#ifndef WAM_SRVS_MESSAGE_CARTVEL_H
#define WAM_SRVS_MESSAGE_CARTVEL_H

#include <ros/service_traits.h>


#include <wam_srvs/CartVelRequest.h>
#include <wam_srvs/CartVelResponse.h>


namespace wam_srvs
{

struct CartVel
{

typedef CartVelRequest Request;
typedef CartVelResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CartVel
} // namespace wam_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::wam_srvs::CartVel > {
  static const char* value()
  {
    return "acd45b1363369bbb5ad0077b51700f8e";
  }

  static const char* value(const ::wam_srvs::CartVel&) { return value(); }
};

template<>
struct DataType< ::wam_srvs::CartVel > {
  static const char* value()
  {
    return "wam_srvs/CartVel";
  }

  static const char* value(const ::wam_srvs::CartVel&) { return value(); }
};


// service_traits::MD5Sum< ::wam_srvs::CartVelRequest> should match 
// service_traits::MD5Sum< ::wam_srvs::CartVel > 
template<>
struct MD5Sum< ::wam_srvs::CartVelRequest>
{
  static const char* value()
  {
    return MD5Sum< ::wam_srvs::CartVel >::value();
  }
  static const char* value(const ::wam_srvs::CartVelRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_srvs::CartVelRequest> should match 
// service_traits::DataType< ::wam_srvs::CartVel > 
template<>
struct DataType< ::wam_srvs::CartVelRequest>
{
  static const char* value()
  {
    return DataType< ::wam_srvs::CartVel >::value();
  }
  static const char* value(const ::wam_srvs::CartVelRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::wam_srvs::CartVelResponse> should match 
// service_traits::MD5Sum< ::wam_srvs::CartVel > 
template<>
struct MD5Sum< ::wam_srvs::CartVelResponse>
{
  static const char* value()
  {
    return MD5Sum< ::wam_srvs::CartVel >::value();
  }
  static const char* value(const ::wam_srvs::CartVelResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_srvs::CartVelResponse> should match 
// service_traits::DataType< ::wam_srvs::CartVel > 
template<>
struct DataType< ::wam_srvs::CartVelResponse>
{
  static const char* value()
  {
    return DataType< ::wam_srvs::CartVel >::value();
  }
  static const char* value(const ::wam_srvs::CartVelResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WAM_SRVS_MESSAGE_CARTVEL_H
