// Generated by gencpp from file wam_srvs/Connect.msg
// DO NOT EDIT!


#ifndef WAM_SRVS_MESSAGE_CONNECT_H
#define WAM_SRVS_MESSAGE_CONNECT_H

#include <ros/service_traits.h>


#include <wam_srvs/ConnectRequest.h>
#include <wam_srvs/ConnectResponse.h>


namespace wam_srvs
{

struct Connect
{

typedef ConnectRequest Request;
typedef ConnectResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Connect
} // namespace wam_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::wam_srvs::Connect > {
  static const char* value()
  {
    return "a31bf7076ca051d3bb47d5d808c4982b";
  }

  static const char* value(const ::wam_srvs::Connect&) { return value(); }
};

template<>
struct DataType< ::wam_srvs::Connect > {
  static const char* value()
  {
    return "wam_srvs/Connect";
  }

  static const char* value(const ::wam_srvs::Connect&) { return value(); }
};


// service_traits::MD5Sum< ::wam_srvs::ConnectRequest> should match 
// service_traits::MD5Sum< ::wam_srvs::Connect > 
template<>
struct MD5Sum< ::wam_srvs::ConnectRequest>
{
  static const char* value()
  {
    return MD5Sum< ::wam_srvs::Connect >::value();
  }
  static const char* value(const ::wam_srvs::ConnectRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_srvs::ConnectRequest> should match 
// service_traits::DataType< ::wam_srvs::Connect > 
template<>
struct DataType< ::wam_srvs::ConnectRequest>
{
  static const char* value()
  {
    return DataType< ::wam_srvs::Connect >::value();
  }
  static const char* value(const ::wam_srvs::ConnectRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::wam_srvs::ConnectResponse> should match 
// service_traits::MD5Sum< ::wam_srvs::Connect > 
template<>
struct MD5Sum< ::wam_srvs::ConnectResponse>
{
  static const char* value()
  {
    return MD5Sum< ::wam_srvs::Connect >::value();
  }
  static const char* value(const ::wam_srvs::ConnectResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_srvs::ConnectResponse> should match 
// service_traits::DataType< ::wam_srvs::Connect > 
template<>
struct DataType< ::wam_srvs::ConnectResponse>
{
  static const char* value()
  {
    return DataType< ::wam_srvs::Connect >::value();
  }
  static const char* value(const ::wam_srvs::ConnectResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WAM_SRVS_MESSAGE_CONNECT_H
