// Generated by gencpp from file wam_srvs/ForceTorqueToolTimeRequest.msg
// DO NOT EDIT!


#ifndef WAM_SRVS_MESSAGE_FORCETORQUETOOLTIMEREQUEST_H
#define WAM_SRVS_MESSAGE_FORCETORQUETOOLTIMEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace wam_srvs
{
template <class ContainerAllocator>
struct ForceTorqueToolTimeRequest_
{
  typedef ForceTorqueToolTimeRequest_<ContainerAllocator> Type;

  ForceTorqueToolTimeRequest_()
    : force()
    , torque()
    , time(0.0)  {
    }
  ForceTorqueToolTimeRequest_(const ContainerAllocator& _alloc)
    : force(_alloc)
    , torque(_alloc)
    , time(0.0)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _force_type;
  _force_type force;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _torque_type;
  _torque_type torque;

   typedef float _time_type;
  _time_type time;





  typedef boost::shared_ptr< ::wam_srvs::ForceTorqueToolTimeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wam_srvs::ForceTorqueToolTimeRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ForceTorqueToolTimeRequest_

typedef ::wam_srvs::ForceTorqueToolTimeRequest_<std::allocator<void> > ForceTorqueToolTimeRequest;

typedef boost::shared_ptr< ::wam_srvs::ForceTorqueToolTimeRequest > ForceTorqueToolTimeRequestPtr;
typedef boost::shared_ptr< ::wam_srvs::ForceTorqueToolTimeRequest const> ForceTorqueToolTimeRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::wam_srvs::ForceTorqueToolTimeRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::wam_srvs::ForceTorqueToolTimeRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace wam_srvs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::wam_srvs::ForceTorqueToolTimeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wam_srvs::ForceTorqueToolTimeRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wam_srvs::ForceTorqueToolTimeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wam_srvs::ForceTorqueToolTimeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wam_srvs::ForceTorqueToolTimeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wam_srvs::ForceTorqueToolTimeRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::wam_srvs::ForceTorqueToolTimeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "85c62cf949363f45f75d48fcf714c6ad";
  }

  static const char* value(const ::wam_srvs::ForceTorqueToolTimeRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x85c62cf949363f45ULL;
  static const uint64_t static_value2 = 0xf75d48fcf714c6adULL;
};

template<class ContainerAllocator>
struct DataType< ::wam_srvs::ForceTorqueToolTimeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "wam_srvs/ForceTorqueToolTimeRequest";
  }

  static const char* value(const ::wam_srvs::ForceTorqueToolTimeRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::wam_srvs::ForceTorqueToolTimeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[]   force\n\
float32[]   torque\n\
float32 time\n\
";
  }

  static const char* value(const ::wam_srvs::ForceTorqueToolTimeRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::wam_srvs::ForceTorqueToolTimeRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.force);
      stream.next(m.torque);
      stream.next(m.time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ForceTorqueToolTimeRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::wam_srvs::ForceTorqueToolTimeRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::wam_srvs::ForceTorqueToolTimeRequest_<ContainerAllocator>& v)
  {
    s << indent << "force[]" << std::endl;
    for (size_t i = 0; i < v.force.size(); ++i)
    {
      s << indent << "  force[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.force[i]);
    }
    s << indent << "torque[]" << std::endl;
    for (size_t i = 0; i < v.torque.size(); ++i)
    {
      s << indent << "  torque[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.torque[i]);
    }
    s << indent << "time: ";
    Printer<float>::stream(s, indent + "  ", v.time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WAM_SRVS_MESSAGE_FORCETORQUETOOLTIMEREQUEST_H
