// Generated by gencpp from file wam_srvs/ForceTorque.msg
// DO NOT EDIT!


#ifndef WAM_SRVS_MESSAGE_FORCETORQUE_H
#define WAM_SRVS_MESSAGE_FORCETORQUE_H

#include <ros/service_traits.h>


#include <wam_srvs/ForceTorqueRequest.h>
#include <wam_srvs/ForceTorqueResponse.h>


namespace wam_srvs
{

struct ForceTorque
{

typedef ForceTorqueRequest Request;
typedef ForceTorqueResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ForceTorque
} // namespace wam_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::wam_srvs::ForceTorque > {
  static const char* value()
  {
    return "8ca0374c6da7480d9143f818b4e38e75";
  }

  static const char* value(const ::wam_srvs::ForceTorque&) { return value(); }
};

template<>
struct DataType< ::wam_srvs::ForceTorque > {
  static const char* value()
  {
    return "wam_srvs/ForceTorque";
  }

  static const char* value(const ::wam_srvs::ForceTorque&) { return value(); }
};


// service_traits::MD5Sum< ::wam_srvs::ForceTorqueRequest> should match 
// service_traits::MD5Sum< ::wam_srvs::ForceTorque > 
template<>
struct MD5Sum< ::wam_srvs::ForceTorqueRequest>
{
  static const char* value()
  {
    return MD5Sum< ::wam_srvs::ForceTorque >::value();
  }
  static const char* value(const ::wam_srvs::ForceTorqueRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_srvs::ForceTorqueRequest> should match 
// service_traits::DataType< ::wam_srvs::ForceTorque > 
template<>
struct DataType< ::wam_srvs::ForceTorqueRequest>
{
  static const char* value()
  {
    return DataType< ::wam_srvs::ForceTorque >::value();
  }
  static const char* value(const ::wam_srvs::ForceTorqueRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::wam_srvs::ForceTorqueResponse> should match 
// service_traits::MD5Sum< ::wam_srvs::ForceTorque > 
template<>
struct MD5Sum< ::wam_srvs::ForceTorqueResponse>
{
  static const char* value()
  {
    return MD5Sum< ::wam_srvs::ForceTorque >::value();
  }
  static const char* value(const ::wam_srvs::ForceTorqueResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_srvs::ForceTorqueResponse> should match 
// service_traits::DataType< ::wam_srvs::ForceTorque > 
template<>
struct DataType< ::wam_srvs::ForceTorqueResponse>
{
  static const char* value()
  {
    return DataType< ::wam_srvs::ForceTorque >::value();
  }
  static const char* value(const ::wam_srvs::ForceTorqueResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WAM_SRVS_MESSAGE_FORCETORQUE_H
