// Generated by gencpp from file wam_srvs/ForceTorqueBaseRequest.msg
// DO NOT EDIT!


#ifndef WAM_SRVS_MESSAGE_FORCETORQUEBASEREQUEST_H
#define WAM_SRVS_MESSAGE_FORCETORQUEBASEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace wam_srvs
{
template <class ContainerAllocator>
struct ForceTorqueBaseRequest_
{
  typedef ForceTorqueBaseRequest_<ContainerAllocator> Type;

  ForceTorqueBaseRequest_()
    : force()
    , torque()
    , kp()
    , kd()
    , mode(0.0)  {
    }
  ForceTorqueBaseRequest_(const ContainerAllocator& _alloc)
    : force(_alloc)
    , torque(_alloc)
    , kp(_alloc)
    , kd(_alloc)
    , mode(0.0)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _force_type;
  _force_type force;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _torque_type;
  _torque_type torque;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _kp_type;
  _kp_type kp;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _kd_type;
  _kd_type kd;

   typedef float _mode_type;
  _mode_type mode;





  typedef boost::shared_ptr< ::wam_srvs::ForceTorqueBaseRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wam_srvs::ForceTorqueBaseRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ForceTorqueBaseRequest_

typedef ::wam_srvs::ForceTorqueBaseRequest_<std::allocator<void> > ForceTorqueBaseRequest;

typedef boost::shared_ptr< ::wam_srvs::ForceTorqueBaseRequest > ForceTorqueBaseRequestPtr;
typedef boost::shared_ptr< ::wam_srvs::ForceTorqueBaseRequest const> ForceTorqueBaseRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::wam_srvs::ForceTorqueBaseRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::wam_srvs::ForceTorqueBaseRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace wam_srvs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::wam_srvs::ForceTorqueBaseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wam_srvs::ForceTorqueBaseRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wam_srvs::ForceTorqueBaseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wam_srvs::ForceTorqueBaseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wam_srvs::ForceTorqueBaseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wam_srvs::ForceTorqueBaseRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::wam_srvs::ForceTorqueBaseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f20a22c7eb9bac32ef69cf5f2e40693f";
  }

  static const char* value(const ::wam_srvs::ForceTorqueBaseRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf20a22c7eb9bac32ULL;
  static const uint64_t static_value2 = 0xef69cf5f2e40693fULL;
};

template<class ContainerAllocator>
struct DataType< ::wam_srvs::ForceTorqueBaseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "wam_srvs/ForceTorqueBaseRequest";
  }

  static const char* value(const ::wam_srvs::ForceTorqueBaseRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::wam_srvs::ForceTorqueBaseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[]   force\n\
float32[]   torque\n\
float32[]   kp\n\
float32[]   kd\n\
float32     mode\n\
";
  }

  static const char* value(const ::wam_srvs::ForceTorqueBaseRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::wam_srvs::ForceTorqueBaseRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.force);
      stream.next(m.torque);
      stream.next(m.kp);
      stream.next(m.kd);
      stream.next(m.mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ForceTorqueBaseRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::wam_srvs::ForceTorqueBaseRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::wam_srvs::ForceTorqueBaseRequest_<ContainerAllocator>& v)
  {
    s << indent << "force[]" << std::endl;
    for (size_t i = 0; i < v.force.size(); ++i)
    {
      s << indent << "  force[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.force[i]);
    }
    s << indent << "torque[]" << std::endl;
    for (size_t i = 0; i < v.torque.size(); ++i)
    {
      s << indent << "  torque[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.torque[i]);
    }
    s << indent << "kp[]" << std::endl;
    for (size_t i = 0; i < v.kp.size(); ++i)
    {
      s << indent << "  kp[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.kp[i]);
    }
    s << indent << "kd[]" << std::endl;
    for (size_t i = 0; i < v.kd.size(); ++i)
    {
      s << indent << "  kd[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.kd[i]);
    }
    s << indent << "mode: ";
    Printer<float>::stream(s, indent + "  ", v.mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WAM_SRVS_MESSAGE_FORCETORQUEBASEREQUEST_H
