// Generated by gencpp from file wam_srvs/ForceTorqueTool.msg
// DO NOT EDIT!


#ifndef WAM_SRVS_MESSAGE_FORCETORQUETOOL_H
#define WAM_SRVS_MESSAGE_FORCETORQUETOOL_H

#include <ros/service_traits.h>


#include <wam_srvs/ForceTorqueToolRequest.h>
#include <wam_srvs/ForceTorqueToolResponse.h>


namespace wam_srvs
{

struct ForceTorqueTool
{

typedef ForceTorqueToolRequest Request;
typedef ForceTorqueToolResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ForceTorqueTool
} // namespace wam_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::wam_srvs::ForceTorqueTool > {
  static const char* value()
  {
    return "85c62cf949363f45f75d48fcf714c6ad";
  }

  static const char* value(const ::wam_srvs::ForceTorqueTool&) { return value(); }
};

template<>
struct DataType< ::wam_srvs::ForceTorqueTool > {
  static const char* value()
  {
    return "wam_srvs/ForceTorqueTool";
  }

  static const char* value(const ::wam_srvs::ForceTorqueTool&) { return value(); }
};


// service_traits::MD5Sum< ::wam_srvs::ForceTorqueToolRequest> should match 
// service_traits::MD5Sum< ::wam_srvs::ForceTorqueTool > 
template<>
struct MD5Sum< ::wam_srvs::ForceTorqueToolRequest>
{
  static const char* value()
  {
    return MD5Sum< ::wam_srvs::ForceTorqueTool >::value();
  }
  static const char* value(const ::wam_srvs::ForceTorqueToolRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_srvs::ForceTorqueToolRequest> should match 
// service_traits::DataType< ::wam_srvs::ForceTorqueTool > 
template<>
struct DataType< ::wam_srvs::ForceTorqueToolRequest>
{
  static const char* value()
  {
    return DataType< ::wam_srvs::ForceTorqueTool >::value();
  }
  static const char* value(const ::wam_srvs::ForceTorqueToolRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::wam_srvs::ForceTorqueToolResponse> should match 
// service_traits::MD5Sum< ::wam_srvs::ForceTorqueTool > 
template<>
struct MD5Sum< ::wam_srvs::ForceTorqueToolResponse>
{
  static const char* value()
  {
    return MD5Sum< ::wam_srvs::ForceTorqueTool >::value();
  }
  static const char* value(const ::wam_srvs::ForceTorqueToolResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_srvs::ForceTorqueToolResponse> should match 
// service_traits::DataType< ::wam_srvs::ForceTorqueTool > 
template<>
struct DataType< ::wam_srvs::ForceTorqueToolResponse>
{
  static const char* value()
  {
    return DataType< ::wam_srvs::ForceTorqueTool >::value();
  }
  static const char* value(const ::wam_srvs::ForceTorqueToolResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WAM_SRVS_MESSAGE_FORCETORQUETOOL_H
