// Generated by gencpp from file wam_srvs/JointMoveBlockRequest.msg
// DO NOT EDIT!


#ifndef WAM_SRVS_MESSAGE_JOINTMOVEBLOCKREQUEST_H
#define WAM_SRVS_MESSAGE_JOINTMOVEBLOCKREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace wam_srvs
{
template <class ContainerAllocator>
struct JointMoveBlockRequest_
{
  typedef JointMoveBlockRequest_<ContainerAllocator> Type;

  JointMoveBlockRequest_()
    : joints()
    , blocking(false)  {
    }
  JointMoveBlockRequest_(const ContainerAllocator& _alloc)
    : joints(_alloc)
    , blocking(false)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _joints_type;
  _joints_type joints;

   typedef uint8_t _blocking_type;
  _blocking_type blocking;





  typedef boost::shared_ptr< ::wam_srvs::JointMoveBlockRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wam_srvs::JointMoveBlockRequest_<ContainerAllocator> const> ConstPtr;

}; // struct JointMoveBlockRequest_

typedef ::wam_srvs::JointMoveBlockRequest_<std::allocator<void> > JointMoveBlockRequest;

typedef boost::shared_ptr< ::wam_srvs::JointMoveBlockRequest > JointMoveBlockRequestPtr;
typedef boost::shared_ptr< ::wam_srvs::JointMoveBlockRequest const> JointMoveBlockRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::wam_srvs::JointMoveBlockRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::wam_srvs::JointMoveBlockRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace wam_srvs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::wam_srvs::JointMoveBlockRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wam_srvs::JointMoveBlockRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wam_srvs::JointMoveBlockRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wam_srvs::JointMoveBlockRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wam_srvs::JointMoveBlockRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wam_srvs::JointMoveBlockRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::wam_srvs::JointMoveBlockRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a35c2d19fdef1f1b6b9cace11da2b5c6";
  }

  static const char* value(const ::wam_srvs::JointMoveBlockRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa35c2d19fdef1f1bULL;
  static const uint64_t static_value2 = 0x6b9cace11da2b5c6ULL;
};

template<class ContainerAllocator>
struct DataType< ::wam_srvs::JointMoveBlockRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "wam_srvs/JointMoveBlockRequest";
  }

  static const char* value(const ::wam_srvs::JointMoveBlockRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::wam_srvs::JointMoveBlockRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] joints\n\
bool blocking\n\
";
  }

  static const char* value(const ::wam_srvs::JointMoveBlockRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::wam_srvs::JointMoveBlockRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joints);
      stream.next(m.blocking);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JointMoveBlockRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::wam_srvs::JointMoveBlockRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::wam_srvs::JointMoveBlockRequest_<ContainerAllocator>& v)
  {
    s << indent << "joints[]" << std::endl;
    for (size_t i = 0; i < v.joints.size(); ++i)
    {
      s << indent << "  joints[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.joints[i]);
    }
    s << indent << "blocking: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.blocking);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WAM_SRVS_MESSAGE_JOINTMOVEBLOCKREQUEST_H
