// Generated by gencpp from file wam_srvs/JointMoveBlock.msg
// DO NOT EDIT!


#ifndef WAM_SRVS_MESSAGE_JOINTMOVEBLOCK_H
#define WAM_SRVS_MESSAGE_JOINTMOVEBLOCK_H

#include <ros/service_traits.h>


#include <wam_srvs/JointMoveBlockRequest.h>
#include <wam_srvs/JointMoveBlockResponse.h>


namespace wam_srvs
{

struct JointMoveBlock
{

typedef JointMoveBlockRequest Request;
typedef JointMoveBlockResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct JointMoveBlock
} // namespace wam_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::wam_srvs::JointMoveBlock > {
  static const char* value()
  {
    return "a35c2d19fdef1f1b6b9cace11da2b5c6";
  }

  static const char* value(const ::wam_srvs::JointMoveBlock&) { return value(); }
};

template<>
struct DataType< ::wam_srvs::JointMoveBlock > {
  static const char* value()
  {
    return "wam_srvs/JointMoveBlock";
  }

  static const char* value(const ::wam_srvs::JointMoveBlock&) { return value(); }
};


// service_traits::MD5Sum< ::wam_srvs::JointMoveBlockRequest> should match 
// service_traits::MD5Sum< ::wam_srvs::JointMoveBlock > 
template<>
struct MD5Sum< ::wam_srvs::JointMoveBlockRequest>
{
  static const char* value()
  {
    return MD5Sum< ::wam_srvs::JointMoveBlock >::value();
  }
  static const char* value(const ::wam_srvs::JointMoveBlockRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_srvs::JointMoveBlockRequest> should match 
// service_traits::DataType< ::wam_srvs::JointMoveBlock > 
template<>
struct DataType< ::wam_srvs::JointMoveBlockRequest>
{
  static const char* value()
  {
    return DataType< ::wam_srvs::JointMoveBlock >::value();
  }
  static const char* value(const ::wam_srvs::JointMoveBlockRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::wam_srvs::JointMoveBlockResponse> should match 
// service_traits::MD5Sum< ::wam_srvs::JointMoveBlock > 
template<>
struct MD5Sum< ::wam_srvs::JointMoveBlockResponse>
{
  static const char* value()
  {
    return MD5Sum< ::wam_srvs::JointMoveBlock >::value();
  }
  static const char* value(const ::wam_srvs::JointMoveBlockResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_srvs::JointMoveBlockResponse> should match 
// service_traits::DataType< ::wam_srvs::JointMoveBlock > 
template<>
struct DataType< ::wam_srvs::JointMoveBlockResponse>
{
  static const char* value()
  {
    return DataType< ::wam_srvs::JointMoveBlock >::value();
  }
  static const char* value(const ::wam_srvs::JointMoveBlockResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WAM_SRVS_MESSAGE_JOINTMOVEBLOCK_H
