// Generated by gencpp from file wam_srvs/JointMove.msg
// DO NOT EDIT!


#ifndef WAM_SRVS_MESSAGE_JOINTMOVE_H
#define WAM_SRVS_MESSAGE_JOINTMOVE_H

#include <ros/service_traits.h>


#include <wam_srvs/JointMoveRequest.h>
#include <wam_srvs/JointMoveResponse.h>


namespace wam_srvs
{

struct JointMove
{

typedef JointMoveRequest Request;
typedef JointMoveResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct JointMove
} // namespace wam_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::wam_srvs::JointMove > {
  static const char* value()
  {
    return "e2a0e438b445b98def0f0ba6a2a85f58";
  }

  static const char* value(const ::wam_srvs::JointMove&) { return value(); }
};

template<>
struct DataType< ::wam_srvs::JointMove > {
  static const char* value()
  {
    return "wam_srvs/JointMove";
  }

  static const char* value(const ::wam_srvs::JointMove&) { return value(); }
};


// service_traits::MD5Sum< ::wam_srvs::JointMoveRequest> should match 
// service_traits::MD5Sum< ::wam_srvs::JointMove > 
template<>
struct MD5Sum< ::wam_srvs::JointMoveRequest>
{
  static const char* value()
  {
    return MD5Sum< ::wam_srvs::JointMove >::value();
  }
  static const char* value(const ::wam_srvs::JointMoveRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_srvs::JointMoveRequest> should match 
// service_traits::DataType< ::wam_srvs::JointMove > 
template<>
struct DataType< ::wam_srvs::JointMoveRequest>
{
  static const char* value()
  {
    return DataType< ::wam_srvs::JointMove >::value();
  }
  static const char* value(const ::wam_srvs::JointMoveRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::wam_srvs::JointMoveResponse> should match 
// service_traits::MD5Sum< ::wam_srvs::JointMove > 
template<>
struct MD5Sum< ::wam_srvs::JointMoveResponse>
{
  static const char* value()
  {
    return MD5Sum< ::wam_srvs::JointMove >::value();
  }
  static const char* value(const ::wam_srvs::JointMoveResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_srvs::JointMoveResponse> should match 
// service_traits::DataType< ::wam_srvs::JointMove > 
template<>
struct DataType< ::wam_srvs::JointMoveResponse>
{
  static const char* value()
  {
    return DataType< ::wam_srvs::JointMove >::value();
  }
  static const char* value(const ::wam_srvs::JointMoveResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WAM_SRVS_MESSAGE_JOINTMOVE_H
