// Generated by gencpp from file wam_srvs/LinkRequest.msg
// DO NOT EDIT!


#ifndef WAM_SRVS_MESSAGE_LINKREQUEST_H
#define WAM_SRVS_MESSAGE_LINKREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace wam_srvs
{
template <class ContainerAllocator>
struct LinkRequest_
{
  typedef LinkRequest_<ContainerAllocator> Type;

  LinkRequest_()
    : remote_ip()  {
    }
  LinkRequest_(const ContainerAllocator& _alloc)
    : remote_ip(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _remote_ip_type;
  _remote_ip_type remote_ip;





  typedef boost::shared_ptr< ::wam_srvs::LinkRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wam_srvs::LinkRequest_<ContainerAllocator> const> ConstPtr;

}; // struct LinkRequest_

typedef ::wam_srvs::LinkRequest_<std::allocator<void> > LinkRequest;

typedef boost::shared_ptr< ::wam_srvs::LinkRequest > LinkRequestPtr;
typedef boost::shared_ptr< ::wam_srvs::LinkRequest const> LinkRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::wam_srvs::LinkRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::wam_srvs::LinkRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace wam_srvs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::wam_srvs::LinkRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wam_srvs::LinkRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wam_srvs::LinkRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wam_srvs::LinkRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wam_srvs::LinkRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wam_srvs::LinkRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::wam_srvs::LinkRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a40ccb098e8ae81c40c4d8ba9679b483";
  }

  static const char* value(const ::wam_srvs::LinkRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa40ccb098e8ae81cULL;
  static const uint64_t static_value2 = 0x40c4d8ba9679b483ULL;
};

template<class ContainerAllocator>
struct DataType< ::wam_srvs::LinkRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "wam_srvs/LinkRequest";
  }

  static const char* value(const ::wam_srvs::LinkRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::wam_srvs::LinkRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string remote_ip\n\
";
  }

  static const char* value(const ::wam_srvs::LinkRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::wam_srvs::LinkRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.remote_ip);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LinkRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::wam_srvs::LinkRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::wam_srvs::LinkRequest_<ContainerAllocator>& v)
  {
    s << indent << "remote_ip: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.remote_ip);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WAM_SRVS_MESSAGE_LINKREQUEST_H
