// Generated by gencpp from file wam_srvs/OrtnGainsRequest.msg
// DO NOT EDIT!


#ifndef WAM_SRVS_MESSAGE_ORTNGAINSREQUEST_H
#define WAM_SRVS_MESSAGE_ORTNGAINSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace wam_srvs
{
template <class ContainerAllocator>
struct OrtnGainsRequest_
{
  typedef OrtnGainsRequest_<ContainerAllocator> Type;

  OrtnGainsRequest_()
    : kp_gain()
    , kd_gain()  {
      kp_gain.assign(0.0);

      kd_gain.assign(0.0);
  }
  OrtnGainsRequest_(const ContainerAllocator& _alloc)
    : kp_gain()
    , kd_gain()  {
  (void)_alloc;
      kp_gain.assign(0.0);

      kd_gain.assign(0.0);
  }



   typedef boost::array<float, 3>  _kp_gain_type;
  _kp_gain_type kp_gain;

   typedef boost::array<float, 3>  _kd_gain_type;
  _kd_gain_type kd_gain;





  typedef boost::shared_ptr< ::wam_srvs::OrtnGainsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wam_srvs::OrtnGainsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct OrtnGainsRequest_

typedef ::wam_srvs::OrtnGainsRequest_<std::allocator<void> > OrtnGainsRequest;

typedef boost::shared_ptr< ::wam_srvs::OrtnGainsRequest > OrtnGainsRequestPtr;
typedef boost::shared_ptr< ::wam_srvs::OrtnGainsRequest const> OrtnGainsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::wam_srvs::OrtnGainsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::wam_srvs::OrtnGainsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace wam_srvs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::wam_srvs::OrtnGainsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wam_srvs::OrtnGainsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wam_srvs::OrtnGainsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wam_srvs::OrtnGainsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wam_srvs::OrtnGainsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wam_srvs::OrtnGainsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::wam_srvs::OrtnGainsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "26320303f516c59455807c34544a7fb5";
  }

  static const char* value(const ::wam_srvs::OrtnGainsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x26320303f516c594ULL;
  static const uint64_t static_value2 = 0x55807c34544a7fb5ULL;
};

template<class ContainerAllocator>
struct DataType< ::wam_srvs::OrtnGainsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "wam_srvs/OrtnGainsRequest";
  }

  static const char* value(const ::wam_srvs::OrtnGainsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::wam_srvs::OrtnGainsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[3] kp_gain\n\
float32[3] kd_gain\n\
";
  }

  static const char* value(const ::wam_srvs::OrtnGainsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::wam_srvs::OrtnGainsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.kp_gain);
      stream.next(m.kd_gain);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct OrtnGainsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::wam_srvs::OrtnGainsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::wam_srvs::OrtnGainsRequest_<ContainerAllocator>& v)
  {
    s << indent << "kp_gain[]" << std::endl;
    for (size_t i = 0; i < v.kp_gain.size(); ++i)
    {
      s << indent << "  kp_gain[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.kp_gain[i]);
    }
    s << indent << "kd_gain[]" << std::endl;
    for (size_t i = 0; i < v.kd_gain.size(); ++i)
    {
      s << indent << "  kd_gain[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.kd_gain[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // WAM_SRVS_MESSAGE_ORTNGAINSREQUEST_H
