// Generated by gencpp from file wam_srvs/OrtnSplitMove.msg
// DO NOT EDIT!


#ifndef WAM_SRVS_MESSAGE_ORTNSPLITMOVE_H
#define WAM_SRVS_MESSAGE_ORTNSPLITMOVE_H

#include <ros/service_traits.h>


#include <wam_srvs/OrtnSplitMoveRequest.h>
#include <wam_srvs/OrtnSplitMoveResponse.h>


namespace wam_srvs
{

struct OrtnSplitMove
{

typedef OrtnSplitMoveRequest Request;
typedef OrtnSplitMoveResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct OrtnSplitMove
} // namespace wam_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::wam_srvs::OrtnSplitMove > {
  static const char* value()
  {
    return "d493f6e469f2b52d5ef0e3d041ef18b7";
  }

  static const char* value(const ::wam_srvs::OrtnSplitMove&) { return value(); }
};

template<>
struct DataType< ::wam_srvs::OrtnSplitMove > {
  static const char* value()
  {
    return "wam_srvs/OrtnSplitMove";
  }

  static const char* value(const ::wam_srvs::OrtnSplitMove&) { return value(); }
};


// service_traits::MD5Sum< ::wam_srvs::OrtnSplitMoveRequest> should match 
// service_traits::MD5Sum< ::wam_srvs::OrtnSplitMove > 
template<>
struct MD5Sum< ::wam_srvs::OrtnSplitMoveRequest>
{
  static const char* value()
  {
    return MD5Sum< ::wam_srvs::OrtnSplitMove >::value();
  }
  static const char* value(const ::wam_srvs::OrtnSplitMoveRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_srvs::OrtnSplitMoveRequest> should match 
// service_traits::DataType< ::wam_srvs::OrtnSplitMove > 
template<>
struct DataType< ::wam_srvs::OrtnSplitMoveRequest>
{
  static const char* value()
  {
    return DataType< ::wam_srvs::OrtnSplitMove >::value();
  }
  static const char* value(const ::wam_srvs::OrtnSplitMoveRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::wam_srvs::OrtnSplitMoveResponse> should match 
// service_traits::MD5Sum< ::wam_srvs::OrtnSplitMove > 
template<>
struct MD5Sum< ::wam_srvs::OrtnSplitMoveResponse>
{
  static const char* value()
  {
    return MD5Sum< ::wam_srvs::OrtnSplitMove >::value();
  }
  static const char* value(const ::wam_srvs::OrtnSplitMoveResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_srvs::OrtnSplitMoveResponse> should match 
// service_traits::DataType< ::wam_srvs::OrtnSplitMove > 
template<>
struct DataType< ::wam_srvs::OrtnSplitMoveResponse>
{
  static const char* value()
  {
    return DataType< ::wam_srvs::OrtnSplitMove >::value();
  }
  static const char* value(const ::wam_srvs::OrtnSplitMoveResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WAM_SRVS_MESSAGE_ORTNSPLITMOVE_H
