// Generated by gencpp from file wam_srvs/Play.msg
// DO NOT EDIT!


#ifndef WAM_SRVS_MESSAGE_PLAY_H
#define WAM_SRVS_MESSAGE_PLAY_H

#include <ros/service_traits.h>


#include <wam_srvs/PlayRequest.h>
#include <wam_srvs/PlayResponse.h>


namespace wam_srvs
{

struct Play
{

typedef PlayRequest Request;
typedef PlayResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Play
} // namespace wam_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::wam_srvs::Play > {
  static const char* value()
  {
    return "1d00cd540af97efeb6b1589112fab63e";
  }

  static const char* value(const ::wam_srvs::Play&) { return value(); }
};

template<>
struct DataType< ::wam_srvs::Play > {
  static const char* value()
  {
    return "wam_srvs/Play";
  }

  static const char* value(const ::wam_srvs::Play&) { return value(); }
};


// service_traits::MD5Sum< ::wam_srvs::PlayRequest> should match 
// service_traits::MD5Sum< ::wam_srvs::Play > 
template<>
struct MD5Sum< ::wam_srvs::PlayRequest>
{
  static const char* value()
  {
    return MD5Sum< ::wam_srvs::Play >::value();
  }
  static const char* value(const ::wam_srvs::PlayRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_srvs::PlayRequest> should match 
// service_traits::DataType< ::wam_srvs::Play > 
template<>
struct DataType< ::wam_srvs::PlayRequest>
{
  static const char* value()
  {
    return DataType< ::wam_srvs::Play >::value();
  }
  static const char* value(const ::wam_srvs::PlayRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::wam_srvs::PlayResponse> should match 
// service_traits::MD5Sum< ::wam_srvs::Play > 
template<>
struct MD5Sum< ::wam_srvs::PlayResponse>
{
  static const char* value()
  {
    return MD5Sum< ::wam_srvs::Play >::value();
  }
  static const char* value(const ::wam_srvs::PlayResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_srvs::PlayResponse> should match 
// service_traits::DataType< ::wam_srvs::Play > 
template<>
struct DataType< ::wam_srvs::PlayResponse>
{
  static const char* value()
  {
    return DataType< ::wam_srvs::Play >::value();
  }
  static const char* value(const ::wam_srvs::PlayResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WAM_SRVS_MESSAGE_PLAY_H
