// Generated by gencpp from file wam_srvs/BHandFingerPosRequest.msg
// DO NOT EDIT!


#ifndef WAM_SRVS_MESSAGE_BHANDFINGERPOSREQUEST_H
#define WAM_SRVS_MESSAGE_BHANDFINGERPOSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace wam_srvs
{
template <class ContainerAllocator>
struct BHandFingerPosRequest_
{
  typedef BHandFingerPosRequest_<ContainerAllocator> Type;

  BHandFingerPosRequest_()
    : radians()  {
      radians.assign(0.0);
  }
  BHandFingerPosRequest_(const ContainerAllocator& _alloc)
    : radians()  {
  (void)_alloc;
      radians.assign(0.0);
  }



   typedef boost::array<float, 3>  _radians_type;
  _radians_type radians;





  typedef boost::shared_ptr< ::wam_srvs::BHandFingerPosRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wam_srvs::BHandFingerPosRequest_<ContainerAllocator> const> ConstPtr;

}; // struct BHandFingerPosRequest_

typedef ::wam_srvs::BHandFingerPosRequest_<std::allocator<void> > BHandFingerPosRequest;

typedef boost::shared_ptr< ::wam_srvs::BHandFingerPosRequest > BHandFingerPosRequestPtr;
typedef boost::shared_ptr< ::wam_srvs::BHandFingerPosRequest const> BHandFingerPosRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::wam_srvs::BHandFingerPosRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::wam_srvs::BHandFingerPosRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace wam_srvs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::wam_srvs::BHandFingerPosRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wam_srvs::BHandFingerPosRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wam_srvs::BHandFingerPosRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wam_srvs::BHandFingerPosRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wam_srvs::BHandFingerPosRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wam_srvs::BHandFingerPosRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::wam_srvs::BHandFingerPosRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b8c122f38450d0302ba1a30c9c588995";
  }

  static const char* value(const ::wam_srvs::BHandFingerPosRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb8c122f38450d030ULL;
  static const uint64_t static_value2 = 0x2ba1a30c9c588995ULL;
};

template<class ContainerAllocator>
struct DataType< ::wam_srvs::BHandFingerPosRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "wam_srvs/BHandFingerPosRequest";
  }

  static const char* value(const ::wam_srvs::BHandFingerPosRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::wam_srvs::BHandFingerPosRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[3] radians\n"
;
  }

  static const char* value(const ::wam_srvs::BHandFingerPosRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::wam_srvs::BHandFingerPosRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.radians);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BHandFingerPosRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::wam_srvs::BHandFingerPosRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::wam_srvs::BHandFingerPosRequest_<ContainerAllocator>& v)
  {
    s << indent << "radians[]" << std::endl;
    for (size_t i = 0; i < v.radians.size(); ++i)
    {
      s << indent << "  radians[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.radians[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // WAM_SRVS_MESSAGE_BHANDFINGERPOSREQUEST_H
