// Generated by gencpp from file wam_srvs/BHandFingerPos.msg
// DO NOT EDIT!


#ifndef WAM_SRVS_MESSAGE_BHANDFINGERPOS_H
#define WAM_SRVS_MESSAGE_BHANDFINGERPOS_H

#include <ros/service_traits.h>


#include <wam_srvs/BHandFingerPosRequest.h>
#include <wam_srvs/BHandFingerPosResponse.h>


namespace wam_srvs
{

struct BHandFingerPos
{

typedef BHandFingerPosRequest Request;
typedef BHandFingerPosResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct BHandFingerPos
} // namespace wam_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::wam_srvs::BHandFingerPos > {
  static const char* value()
  {
    return "b8c122f38450d0302ba1a30c9c588995";
  }

  static const char* value(const ::wam_srvs::BHandFingerPos&) { return value(); }
};

template<>
struct DataType< ::wam_srvs::BHandFingerPos > {
  static const char* value()
  {
    return "wam_srvs/BHandFingerPos";
  }

  static const char* value(const ::wam_srvs::BHandFingerPos&) { return value(); }
};


// service_traits::MD5Sum< ::wam_srvs::BHandFingerPosRequest> should match 
// service_traits::MD5Sum< ::wam_srvs::BHandFingerPos > 
template<>
struct MD5Sum< ::wam_srvs::BHandFingerPosRequest>
{
  static const char* value()
  {
    return MD5Sum< ::wam_srvs::BHandFingerPos >::value();
  }
  static const char* value(const ::wam_srvs::BHandFingerPosRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_srvs::BHandFingerPosRequest> should match 
// service_traits::DataType< ::wam_srvs::BHandFingerPos > 
template<>
struct DataType< ::wam_srvs::BHandFingerPosRequest>
{
  static const char* value()
  {
    return DataType< ::wam_srvs::BHandFingerPos >::value();
  }
  static const char* value(const ::wam_srvs::BHandFingerPosRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::wam_srvs::BHandFingerPosResponse> should match 
// service_traits::MD5Sum< ::wam_srvs::BHandFingerPos > 
template<>
struct MD5Sum< ::wam_srvs::BHandFingerPosResponse>
{
  static const char* value()
  {
    return MD5Sum< ::wam_srvs::BHandFingerPos >::value();
  }
  static const char* value(const ::wam_srvs::BHandFingerPosResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_srvs::BHandFingerPosResponse> should match 
// service_traits::DataType< ::wam_srvs::BHandFingerPos > 
template<>
struct DataType< ::wam_srvs::BHandFingerPosResponse>
{
  static const char* value()
  {
    return DataType< ::wam_srvs::BHandFingerPos >::value();
  }
  static const char* value(const ::wam_srvs::BHandFingerPosResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WAM_SRVS_MESSAGE_BHANDFINGERPOS_H
