// Generated by gencpp from file wam_srvs/BHandGraspVel.msg
// DO NOT EDIT!


#ifndef WAM_SRVS_MESSAGE_BHANDGRASPVEL_H
#define WAM_SRVS_MESSAGE_BHANDGRASPVEL_H

#include <ros/service_traits.h>


#include <wam_srvs/BHandGraspVelRequest.h>
#include <wam_srvs/BHandGraspVelResponse.h>


namespace wam_srvs
{

struct BHandGraspVel
{

typedef BHandGraspVelRequest Request;
typedef BHandGraspVelResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct BHandGraspVel
} // namespace wam_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::wam_srvs::BHandGraspVel > {
  static const char* value()
  {
    return "e4ff88b32504f688719a85e0753f63ce";
  }

  static const char* value(const ::wam_srvs::BHandGraspVel&) { return value(); }
};

template<>
struct DataType< ::wam_srvs::BHandGraspVel > {
  static const char* value()
  {
    return "wam_srvs/BHandGraspVel";
  }

  static const char* value(const ::wam_srvs::BHandGraspVel&) { return value(); }
};


// service_traits::MD5Sum< ::wam_srvs::BHandGraspVelRequest> should match 
// service_traits::MD5Sum< ::wam_srvs::BHandGraspVel > 
template<>
struct MD5Sum< ::wam_srvs::BHandGraspVelRequest>
{
  static const char* value()
  {
    return MD5Sum< ::wam_srvs::BHandGraspVel >::value();
  }
  static const char* value(const ::wam_srvs::BHandGraspVelRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_srvs::BHandGraspVelRequest> should match 
// service_traits::DataType< ::wam_srvs::BHandGraspVel > 
template<>
struct DataType< ::wam_srvs::BHandGraspVelRequest>
{
  static const char* value()
  {
    return DataType< ::wam_srvs::BHandGraspVel >::value();
  }
  static const char* value(const ::wam_srvs::BHandGraspVelRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::wam_srvs::BHandGraspVelResponse> should match 
// service_traits::MD5Sum< ::wam_srvs::BHandGraspVel > 
template<>
struct MD5Sum< ::wam_srvs::BHandGraspVelResponse>
{
  static const char* value()
  {
    return MD5Sum< ::wam_srvs::BHandGraspVel >::value();
  }
  static const char* value(const ::wam_srvs::BHandGraspVelResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_srvs::BHandGraspVelResponse> should match 
// service_traits::DataType< ::wam_srvs::BHandGraspVel > 
template<>
struct DataType< ::wam_srvs::BHandGraspVelResponse>
{
  static const char* value()
  {
    return DataType< ::wam_srvs::BHandGraspVel >::value();
  }
  static const char* value(const ::wam_srvs::BHandGraspVelResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WAM_SRVS_MESSAGE_BHANDGRASPVEL_H
