// Generated by gencpp from file wam_srvs/BHandGraspPos.msg
// DO NOT EDIT!


#ifndef WAM_SRVS_MESSAGE_BHANDGRASPPOS_H
#define WAM_SRVS_MESSAGE_BHANDGRASPPOS_H

#include <ros/service_traits.h>


#include <wam_srvs/BHandGraspPosRequest.h>
#include <wam_srvs/BHandGraspPosResponse.h>


namespace wam_srvs
{

struct BHandGraspPos
{

typedef BHandGraspPosRequest Request;
typedef BHandGraspPosResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct BHandGraspPos
} // namespace wam_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::wam_srvs::BHandGraspPos > {
  static const char* value()
  {
    return "718158cfca4f89c6952f799c53697f42";
  }

  static const char* value(const ::wam_srvs::BHandGraspPos&) { return value(); }
};

template<>
struct DataType< ::wam_srvs::BHandGraspPos > {
  static const char* value()
  {
    return "wam_srvs/BHandGraspPos";
  }

  static const char* value(const ::wam_srvs::BHandGraspPos&) { return value(); }
};


// service_traits::MD5Sum< ::wam_srvs::BHandGraspPosRequest> should match 
// service_traits::MD5Sum< ::wam_srvs::BHandGraspPos > 
template<>
struct MD5Sum< ::wam_srvs::BHandGraspPosRequest>
{
  static const char* value()
  {
    return MD5Sum< ::wam_srvs::BHandGraspPos >::value();
  }
  static const char* value(const ::wam_srvs::BHandGraspPosRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_srvs::BHandGraspPosRequest> should match 
// service_traits::DataType< ::wam_srvs::BHandGraspPos > 
template<>
struct DataType< ::wam_srvs::BHandGraspPosRequest>
{
  static const char* value()
  {
    return DataType< ::wam_srvs::BHandGraspPos >::value();
  }
  static const char* value(const ::wam_srvs::BHandGraspPosRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::wam_srvs::BHandGraspPosResponse> should match 
// service_traits::MD5Sum< ::wam_srvs::BHandGraspPos > 
template<>
struct MD5Sum< ::wam_srvs::BHandGraspPosResponse>
{
  static const char* value()
  {
    return MD5Sum< ::wam_srvs::BHandGraspPos >::value();
  }
  static const char* value(const ::wam_srvs::BHandGraspPosResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_srvs::BHandGraspPosResponse> should match 
// service_traits::DataType< ::wam_srvs::BHandGraspPos > 
template<>
struct DataType< ::wam_srvs::BHandGraspPosResponse>
{
  static const char* value()
  {
    return DataType< ::wam_srvs::BHandGraspPos >::value();
  }
  static const char* value(const ::wam_srvs::BHandGraspPosResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WAM_SRVS_MESSAGE_BHANDGRASPPOS_H
