// Generated by gencpp from file wam_srvs/CartVelRequest.msg
// DO NOT EDIT!


#ifndef WAM_SRVS_MESSAGE_CARTVELREQUEST_H
#define WAM_SRVS_MESSAGE_CARTVELREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace wam_srvs
{
template <class ContainerAllocator>
struct CartVelRequest_
{
  typedef CartVelRequest_<ContainerAllocator> Type;

  CartVelRequest_()
    : v_direction()
    , v_magnitude(0.0)
    , kp(0.0)
    , visual_system(false)  {
      v_direction.assign(0.0);
  }
  CartVelRequest_(const ContainerAllocator& _alloc)
    : v_direction()
    , v_magnitude(0.0)
    , kp(0.0)
    , visual_system(false)  {
  (void)_alloc;
      v_direction.assign(0.0);
  }



   typedef boost::array<float, 3>  _v_direction_type;
  _v_direction_type v_direction;

   typedef float _v_magnitude_type;
  _v_magnitude_type v_magnitude;

   typedef float _kp_type;
  _kp_type kp;

   typedef uint8_t _visual_system_type;
  _visual_system_type visual_system;





  typedef boost::shared_ptr< ::wam_srvs::CartVelRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wam_srvs::CartVelRequest_<ContainerAllocator> const> ConstPtr;

}; // struct CartVelRequest_

typedef ::wam_srvs::CartVelRequest_<std::allocator<void> > CartVelRequest;

typedef boost::shared_ptr< ::wam_srvs::CartVelRequest > CartVelRequestPtr;
typedef boost::shared_ptr< ::wam_srvs::CartVelRequest const> CartVelRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::wam_srvs::CartVelRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::wam_srvs::CartVelRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace wam_srvs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::wam_srvs::CartVelRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wam_srvs::CartVelRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wam_srvs::CartVelRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wam_srvs::CartVelRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wam_srvs::CartVelRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wam_srvs::CartVelRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::wam_srvs::CartVelRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "acd45b1363369bbb5ad0077b51700f8e";
  }

  static const char* value(const ::wam_srvs::CartVelRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xacd45b1363369bbbULL;
  static const uint64_t static_value2 = 0x5ad0077b51700f8eULL;
};

template<class ContainerAllocator>
struct DataType< ::wam_srvs::CartVelRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "wam_srvs/CartVelRequest";
  }

  static const char* value(const ::wam_srvs::CartVelRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::wam_srvs::CartVelRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[3] v_direction\n"
"float32 v_magnitude\n"
"float32 kp\n"
"bool visual_system\n"
;
  }

  static const char* value(const ::wam_srvs::CartVelRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::wam_srvs::CartVelRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.v_direction);
      stream.next(m.v_magnitude);
      stream.next(m.kp);
      stream.next(m.visual_system);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CartVelRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::wam_srvs::CartVelRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::wam_srvs::CartVelRequest_<ContainerAllocator>& v)
  {
    s << indent << "v_direction[]" << std::endl;
    for (size_t i = 0; i < v.v_direction.size(); ++i)
    {
      s << indent << "  v_direction[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.v_direction[i]);
    }
    s << indent << "v_magnitude: ";
    Printer<float>::stream(s, indent + "  ", v.v_magnitude);
    s << indent << "kp: ";
    Printer<float>::stream(s, indent + "  ", v.kp);
    s << indent << "visual_system: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.visual_system);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WAM_SRVS_MESSAGE_CARTVELREQUEST_H
