// Generated by gencpp from file wam_srvs/ForceTorqueToolTime.msg
// DO NOT EDIT!


#ifndef WAM_SRVS_MESSAGE_FORCETORQUETOOLTIME_H
#define WAM_SRVS_MESSAGE_FORCETORQUETOOLTIME_H

#include <ros/service_traits.h>


#include <wam_srvs/ForceTorqueToolTimeRequest.h>
#include <wam_srvs/ForceTorqueToolTimeResponse.h>


namespace wam_srvs
{

struct ForceTorqueToolTime
{

typedef ForceTorqueToolTimeRequest Request;
typedef ForceTorqueToolTimeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ForceTorqueToolTime
} // namespace wam_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::wam_srvs::ForceTorqueToolTime > {
  static const char* value()
  {
    return "85c62cf949363f45f75d48fcf714c6ad";
  }

  static const char* value(const ::wam_srvs::ForceTorqueToolTime&) { return value(); }
};

template<>
struct DataType< ::wam_srvs::ForceTorqueToolTime > {
  static const char* value()
  {
    return "wam_srvs/ForceTorqueToolTime";
  }

  static const char* value(const ::wam_srvs::ForceTorqueToolTime&) { return value(); }
};


// service_traits::MD5Sum< ::wam_srvs::ForceTorqueToolTimeRequest> should match 
// service_traits::MD5Sum< ::wam_srvs::ForceTorqueToolTime > 
template<>
struct MD5Sum< ::wam_srvs::ForceTorqueToolTimeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::wam_srvs::ForceTorqueToolTime >::value();
  }
  static const char* value(const ::wam_srvs::ForceTorqueToolTimeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_srvs::ForceTorqueToolTimeRequest> should match 
// service_traits::DataType< ::wam_srvs::ForceTorqueToolTime > 
template<>
struct DataType< ::wam_srvs::ForceTorqueToolTimeRequest>
{
  static const char* value()
  {
    return DataType< ::wam_srvs::ForceTorqueToolTime >::value();
  }
  static const char* value(const ::wam_srvs::ForceTorqueToolTimeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::wam_srvs::ForceTorqueToolTimeResponse> should match 
// service_traits::MD5Sum< ::wam_srvs::ForceTorqueToolTime > 
template<>
struct MD5Sum< ::wam_srvs::ForceTorqueToolTimeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::wam_srvs::ForceTorqueToolTime >::value();
  }
  static const char* value(const ::wam_srvs::ForceTorqueToolTimeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_srvs::ForceTorqueToolTimeResponse> should match 
// service_traits::DataType< ::wam_srvs::ForceTorqueToolTime > 
template<>
struct DataType< ::wam_srvs::ForceTorqueToolTimeResponse>
{
  static const char* value()
  {
    return DataType< ::wam_srvs::ForceTorqueToolTime >::value();
  }
  static const char* value(const ::wam_srvs::ForceTorqueToolTimeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WAM_SRVS_MESSAGE_FORCETORQUETOOLTIME_H
