// Generated by gencpp from file wam_srvs/HapticSphereRequest.msg
// DO NOT EDIT!


#ifndef WAM_SRVS_MESSAGE_HAPTICSPHEREREQUEST_H
#define WAM_SRVS_MESSAGE_HAPTICSPHEREREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace wam_srvs
{
template <class ContainerAllocator>
struct HapticSphereRequest_
{
  typedef HapticSphereRequest_<ContainerAllocator> Type;

  HapticSphereRequest_()
    : radius(0.0)
    , kp(0.0)
    , kd(0.0)
    , trigger(false)  {
    }
  HapticSphereRequest_(const ContainerAllocator& _alloc)
    : radius(0.0)
    , kp(0.0)
    , kd(0.0)
    , trigger(false)  {
  (void)_alloc;
    }



   typedef float _radius_type;
  _radius_type radius;

   typedef float _kp_type;
  _kp_type kp;

   typedef float _kd_type;
  _kd_type kd;

   typedef uint8_t _trigger_type;
  _trigger_type trigger;





  typedef boost::shared_ptr< ::wam_srvs::HapticSphereRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wam_srvs::HapticSphereRequest_<ContainerAllocator> const> ConstPtr;

}; // struct HapticSphereRequest_

typedef ::wam_srvs::HapticSphereRequest_<std::allocator<void> > HapticSphereRequest;

typedef boost::shared_ptr< ::wam_srvs::HapticSphereRequest > HapticSphereRequestPtr;
typedef boost::shared_ptr< ::wam_srvs::HapticSphereRequest const> HapticSphereRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::wam_srvs::HapticSphereRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::wam_srvs::HapticSphereRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace wam_srvs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::wam_srvs::HapticSphereRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wam_srvs::HapticSphereRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wam_srvs::HapticSphereRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wam_srvs::HapticSphereRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wam_srvs::HapticSphereRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wam_srvs::HapticSphereRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::wam_srvs::HapticSphereRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "26022341c3342c1799fc44701262bee2";
  }

  static const char* value(const ::wam_srvs::HapticSphereRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x26022341c3342c17ULL;
  static const uint64_t static_value2 = 0x99fc44701262bee2ULL;
};

template<class ContainerAllocator>
struct DataType< ::wam_srvs::HapticSphereRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "wam_srvs/HapticSphereRequest";
  }

  static const char* value(const ::wam_srvs::HapticSphereRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::wam_srvs::HapticSphereRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 radius\n"
"float32 kp\n"
"float32 kd\n"
"bool trigger\n"
;
  }

  static const char* value(const ::wam_srvs::HapticSphereRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::wam_srvs::HapticSphereRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.radius);
      stream.next(m.kp);
      stream.next(m.kd);
      stream.next(m.trigger);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HapticSphereRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::wam_srvs::HapticSphereRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::wam_srvs::HapticSphereRequest_<ContainerAllocator>& v)
  {
    s << indent << "radius: ";
    Printer<float>::stream(s, indent + "  ", v.radius);
    s << indent << "kp: ";
    Printer<float>::stream(s, indent + "  ", v.kp);
    s << indent << "kd: ";
    Printer<float>::stream(s, indent + "  ", v.kd);
    s << indent << "trigger: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.trigger);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WAM_SRVS_MESSAGE_HAPTICSPHEREREQUEST_H
