// Generated by gencpp from file wam_srvs/HoldGains.msg
// DO NOT EDIT!


#ifndef WAM_SRVS_MESSAGE_HOLDGAINS_H
#define WAM_SRVS_MESSAGE_HOLDGAINS_H

#include <ros/service_traits.h>


#include <wam_srvs/HoldGainsRequest.h>
#include <wam_srvs/HoldGainsResponse.h>


namespace wam_srvs
{

struct HoldGains
{

typedef HoldGainsRequest Request;
typedef HoldGainsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct HoldGains
} // namespace wam_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::wam_srvs::HoldGains > {
  static const char* value()
  {
    return "2321330bd020469c41b8f08acef334cb";
  }

  static const char* value(const ::wam_srvs::HoldGains&) { return value(); }
};

template<>
struct DataType< ::wam_srvs::HoldGains > {
  static const char* value()
  {
    return "wam_srvs/HoldGains";
  }

  static const char* value(const ::wam_srvs::HoldGains&) { return value(); }
};


// service_traits::MD5Sum< ::wam_srvs::HoldGainsRequest> should match 
// service_traits::MD5Sum< ::wam_srvs::HoldGains > 
template<>
struct MD5Sum< ::wam_srvs::HoldGainsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::wam_srvs::HoldGains >::value();
  }
  static const char* value(const ::wam_srvs::HoldGainsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_srvs::HoldGainsRequest> should match 
// service_traits::DataType< ::wam_srvs::HoldGains > 
template<>
struct DataType< ::wam_srvs::HoldGainsRequest>
{
  static const char* value()
  {
    return DataType< ::wam_srvs::HoldGains >::value();
  }
  static const char* value(const ::wam_srvs::HoldGainsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::wam_srvs::HoldGainsResponse> should match 
// service_traits::MD5Sum< ::wam_srvs::HoldGains > 
template<>
struct MD5Sum< ::wam_srvs::HoldGainsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::wam_srvs::HoldGains >::value();
  }
  static const char* value(const ::wam_srvs::HoldGainsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_srvs::HoldGainsResponse> should match 
// service_traits::DataType< ::wam_srvs::HoldGains > 
template<>
struct DataType< ::wam_srvs::HoldGainsResponse>
{
  static const char* value()
  {
    return DataType< ::wam_srvs::HoldGains >::value();
  }
  static const char* value(const ::wam_srvs::HoldGainsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WAM_SRVS_MESSAGE_HOLDGAINS_H
