// Generated by gencpp from file wam_srvs/HoldGainsRequest.msg
// DO NOT EDIT!


#ifndef WAM_SRVS_MESSAGE_HOLDGAINSREQUEST_H
#define WAM_SRVS_MESSAGE_HOLDGAINSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace wam_srvs
{
template <class ContainerAllocator>
struct HoldGainsRequest_
{
  typedef HoldGainsRequest_<ContainerAllocator> Type;

  HoldGainsRequest_()
    : hold(false)
    , kp()
    , kd()  {
      kp.assign(0.0);

      kd.assign(0.0);
  }
  HoldGainsRequest_(const ContainerAllocator& _alloc)
    : hold(false)
    , kp()
    , kd()  {
  (void)_alloc;
      kp.assign(0.0);

      kd.assign(0.0);
  }



   typedef uint8_t _hold_type;
  _hold_type hold;

   typedef boost::array<float, 3>  _kp_type;
  _kp_type kp;

   typedef boost::array<float, 3>  _kd_type;
  _kd_type kd;





  typedef boost::shared_ptr< ::wam_srvs::HoldGainsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wam_srvs::HoldGainsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct HoldGainsRequest_

typedef ::wam_srvs::HoldGainsRequest_<std::allocator<void> > HoldGainsRequest;

typedef boost::shared_ptr< ::wam_srvs::HoldGainsRequest > HoldGainsRequestPtr;
typedef boost::shared_ptr< ::wam_srvs::HoldGainsRequest const> HoldGainsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::wam_srvs::HoldGainsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::wam_srvs::HoldGainsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace wam_srvs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::wam_srvs::HoldGainsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wam_srvs::HoldGainsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wam_srvs::HoldGainsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wam_srvs::HoldGainsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wam_srvs::HoldGainsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wam_srvs::HoldGainsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::wam_srvs::HoldGainsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2321330bd020469c41b8f08acef334cb";
  }

  static const char* value(const ::wam_srvs::HoldGainsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2321330bd020469cULL;
  static const uint64_t static_value2 = 0x41b8f08acef334cbULL;
};

template<class ContainerAllocator>
struct DataType< ::wam_srvs::HoldGainsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "wam_srvs/HoldGainsRequest";
  }

  static const char* value(const ::wam_srvs::HoldGainsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::wam_srvs::HoldGainsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool hold\n"
"float32[3] kp\n"
"float32[3] kd\n"
;
  }

  static const char* value(const ::wam_srvs::HoldGainsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::wam_srvs::HoldGainsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.hold);
      stream.next(m.kp);
      stream.next(m.kd);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HoldGainsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::wam_srvs::HoldGainsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::wam_srvs::HoldGainsRequest_<ContainerAllocator>& v)
  {
    s << indent << "hold: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.hold);
    s << indent << "kp[]" << std::endl;
    for (size_t i = 0; i < v.kp.size(); ++i)
    {
      s << indent << "  kp[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.kp[i]);
    }
    s << indent << "kd[]" << std::endl;
    for (size_t i = 0; i < v.kd.size(); ++i)
    {
      s << indent << "  kd[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.kd[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // WAM_SRVS_MESSAGE_HOLDGAINSREQUEST_H
