// Generated by gencpp from file wam_srvs/Link.msg
// DO NOT EDIT!


#ifndef WAM_SRVS_MESSAGE_LINK_H
#define WAM_SRVS_MESSAGE_LINK_H

#include <ros/service_traits.h>


#include <wam_srvs/LinkRequest.h>
#include <wam_srvs/LinkResponse.h>


namespace wam_srvs
{

struct Link
{

typedef LinkRequest Request;
typedef LinkResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Link
} // namespace wam_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::wam_srvs::Link > {
  static const char* value()
  {
    return "a40ccb098e8ae81c40c4d8ba9679b483";
  }

  static const char* value(const ::wam_srvs::Link&) { return value(); }
};

template<>
struct DataType< ::wam_srvs::Link > {
  static const char* value()
  {
    return "wam_srvs/Link";
  }

  static const char* value(const ::wam_srvs::Link&) { return value(); }
};


// service_traits::MD5Sum< ::wam_srvs::LinkRequest> should match 
// service_traits::MD5Sum< ::wam_srvs::Link > 
template<>
struct MD5Sum< ::wam_srvs::LinkRequest>
{
  static const char* value()
  {
    return MD5Sum< ::wam_srvs::Link >::value();
  }
  static const char* value(const ::wam_srvs::LinkRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_srvs::LinkRequest> should match 
// service_traits::DataType< ::wam_srvs::Link > 
template<>
struct DataType< ::wam_srvs::LinkRequest>
{
  static const char* value()
  {
    return DataType< ::wam_srvs::Link >::value();
  }
  static const char* value(const ::wam_srvs::LinkRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::wam_srvs::LinkResponse> should match 
// service_traits::MD5Sum< ::wam_srvs::Link > 
template<>
struct MD5Sum< ::wam_srvs::LinkResponse>
{
  static const char* value()
  {
    return MD5Sum< ::wam_srvs::Link >::value();
  }
  static const char* value(const ::wam_srvs::LinkResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_srvs::LinkResponse> should match 
// service_traits::DataType< ::wam_srvs::Link > 
template<>
struct DataType< ::wam_srvs::LinkResponse>
{
  static const char* value()
  {
    return DataType< ::wam_srvs::Link >::value();
  }
  static const char* value(const ::wam_srvs::LinkResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WAM_SRVS_MESSAGE_LINK_H
