// Generated by gencpp from file wam_srvs/OrtnMoveRequest.msg
// DO NOT EDIT!


#ifndef WAM_SRVS_MESSAGE_ORTNMOVEREQUEST_H
#define WAM_SRVS_MESSAGE_ORTNMOVEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace wam_srvs
{
template <class ContainerAllocator>
struct OrtnMoveRequest_
{
  typedef OrtnMoveRequest_<ContainerAllocator> Type;

  OrtnMoveRequest_()
    : orientation()  {
      orientation.assign(0.0);
  }
  OrtnMoveRequest_(const ContainerAllocator& _alloc)
    : orientation()  {
  (void)_alloc;
      orientation.assign(0.0);
  }



   typedef boost::array<float, 4>  _orientation_type;
  _orientation_type orientation;





  typedef boost::shared_ptr< ::wam_srvs::OrtnMoveRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wam_srvs::OrtnMoveRequest_<ContainerAllocator> const> ConstPtr;

}; // struct OrtnMoveRequest_

typedef ::wam_srvs::OrtnMoveRequest_<std::allocator<void> > OrtnMoveRequest;

typedef boost::shared_ptr< ::wam_srvs::OrtnMoveRequest > OrtnMoveRequestPtr;
typedef boost::shared_ptr< ::wam_srvs::OrtnMoveRequest const> OrtnMoveRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::wam_srvs::OrtnMoveRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::wam_srvs::OrtnMoveRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace wam_srvs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::wam_srvs::OrtnMoveRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wam_srvs::OrtnMoveRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wam_srvs::OrtnMoveRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wam_srvs::OrtnMoveRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wam_srvs::OrtnMoveRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wam_srvs::OrtnMoveRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::wam_srvs::OrtnMoveRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "86f723fe9a4be8979be87cd065276584";
  }

  static const char* value(const ::wam_srvs::OrtnMoveRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x86f723fe9a4be897ULL;
  static const uint64_t static_value2 = 0x9be87cd065276584ULL;
};

template<class ContainerAllocator>
struct DataType< ::wam_srvs::OrtnMoveRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "wam_srvs/OrtnMoveRequest";
  }

  static const char* value(const ::wam_srvs::OrtnMoveRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::wam_srvs::OrtnMoveRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[4] orientation\n"
;
  }

  static const char* value(const ::wam_srvs::OrtnMoveRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::wam_srvs::OrtnMoveRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.orientation);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct OrtnMoveRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::wam_srvs::OrtnMoveRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::wam_srvs::OrtnMoveRequest_<ContainerAllocator>& v)
  {
    s << indent << "orientation[]" << std::endl;
    for (size_t i = 0; i < v.orientation.size(); ++i)
    {
      s << indent << "  orientation[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.orientation[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // WAM_SRVS_MESSAGE_ORTNMOVEREQUEST_H
