// Generated by gencpp from file wam_srvs/OrtnGains.msg
// DO NOT EDIT!


#ifndef WAM_SRVS_MESSAGE_ORTNGAINS_H
#define WAM_SRVS_MESSAGE_ORTNGAINS_H

#include <ros/service_traits.h>


#include <wam_srvs/OrtnGainsRequest.h>
#include <wam_srvs/OrtnGainsResponse.h>


namespace wam_srvs
{

struct OrtnGains
{

typedef OrtnGainsRequest Request;
typedef OrtnGainsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct OrtnGains
} // namespace wam_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::wam_srvs::OrtnGains > {
  static const char* value()
  {
    return "26320303f516c59455807c34544a7fb5";
  }

  static const char* value(const ::wam_srvs::OrtnGains&) { return value(); }
};

template<>
struct DataType< ::wam_srvs::OrtnGains > {
  static const char* value()
  {
    return "wam_srvs/OrtnGains";
  }

  static const char* value(const ::wam_srvs::OrtnGains&) { return value(); }
};


// service_traits::MD5Sum< ::wam_srvs::OrtnGainsRequest> should match 
// service_traits::MD5Sum< ::wam_srvs::OrtnGains > 
template<>
struct MD5Sum< ::wam_srvs::OrtnGainsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::wam_srvs::OrtnGains >::value();
  }
  static const char* value(const ::wam_srvs::OrtnGainsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_srvs::OrtnGainsRequest> should match 
// service_traits::DataType< ::wam_srvs::OrtnGains > 
template<>
struct DataType< ::wam_srvs::OrtnGainsRequest>
{
  static const char* value()
  {
    return DataType< ::wam_srvs::OrtnGains >::value();
  }
  static const char* value(const ::wam_srvs::OrtnGainsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::wam_srvs::OrtnGainsResponse> should match 
// service_traits::MD5Sum< ::wam_srvs::OrtnGains > 
template<>
struct MD5Sum< ::wam_srvs::OrtnGainsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::wam_srvs::OrtnGains >::value();
  }
  static const char* value(const ::wam_srvs::OrtnGainsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_srvs::OrtnGainsResponse> should match 
// service_traits::DataType< ::wam_srvs::OrtnGains > 
template<>
struct DataType< ::wam_srvs::OrtnGainsResponse>
{
  static const char* value()
  {
    return DataType< ::wam_srvs::OrtnGains >::value();
  }
  static const char* value(const ::wam_srvs::OrtnGainsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WAM_SRVS_MESSAGE_ORTNGAINS_H
