// Generated by gencpp from file wam_srvs/OrtnMove.msg
// DO NOT EDIT!


#ifndef WAM_SRVS_MESSAGE_ORTNMOVE_H
#define WAM_SRVS_MESSAGE_ORTNMOVE_H

#include <ros/service_traits.h>


#include <wam_srvs/OrtnMoveRequest.h>
#include <wam_srvs/OrtnMoveResponse.h>


namespace wam_srvs
{

struct OrtnMove
{

typedef OrtnMoveRequest Request;
typedef OrtnMoveResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct OrtnMove
} // namespace wam_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::wam_srvs::OrtnMove > {
  static const char* value()
  {
    return "86f723fe9a4be8979be87cd065276584";
  }

  static const char* value(const ::wam_srvs::OrtnMove&) { return value(); }
};

template<>
struct DataType< ::wam_srvs::OrtnMove > {
  static const char* value()
  {
    return "wam_srvs/OrtnMove";
  }

  static const char* value(const ::wam_srvs::OrtnMove&) { return value(); }
};


// service_traits::MD5Sum< ::wam_srvs::OrtnMoveRequest> should match 
// service_traits::MD5Sum< ::wam_srvs::OrtnMove > 
template<>
struct MD5Sum< ::wam_srvs::OrtnMoveRequest>
{
  static const char* value()
  {
    return MD5Sum< ::wam_srvs::OrtnMove >::value();
  }
  static const char* value(const ::wam_srvs::OrtnMoveRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_srvs::OrtnMoveRequest> should match 
// service_traits::DataType< ::wam_srvs::OrtnMove > 
template<>
struct DataType< ::wam_srvs::OrtnMoveRequest>
{
  static const char* value()
  {
    return DataType< ::wam_srvs::OrtnMove >::value();
  }
  static const char* value(const ::wam_srvs::OrtnMoveRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::wam_srvs::OrtnMoveResponse> should match 
// service_traits::MD5Sum< ::wam_srvs::OrtnMove > 
template<>
struct MD5Sum< ::wam_srvs::OrtnMoveResponse>
{
  static const char* value()
  {
    return MD5Sum< ::wam_srvs::OrtnMove >::value();
  }
  static const char* value(const ::wam_srvs::OrtnMoveResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_srvs::OrtnMoveResponse> should match 
// service_traits::DataType< ::wam_srvs::OrtnMove > 
template<>
struct DataType< ::wam_srvs::OrtnMoveResponse>
{
  static const char* value()
  {
    return DataType< ::wam_srvs::OrtnMove >::value();
  }
  static const char* value(const ::wam_srvs::OrtnMoveResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WAM_SRVS_MESSAGE_ORTNMOVE_H
