// Generated by gencpp from file wam_srvs/Teach.msg
// DO NOT EDIT!


#ifndef WAM_SRVS_MESSAGE_TEACH_H
#define WAM_SRVS_MESSAGE_TEACH_H

#include <ros/service_traits.h>


#include <wam_srvs/TeachRequest.h>
#include <wam_srvs/TeachResponse.h>


namespace wam_srvs
{

struct Teach
{

typedef TeachRequest Request;
typedef TeachResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Teach
} // namespace wam_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::wam_srvs::Teach > {
  static const char* value()
  {
    return "1d00cd540af97efeb6b1589112fab63e";
  }

  static const char* value(const ::wam_srvs::Teach&) { return value(); }
};

template<>
struct DataType< ::wam_srvs::Teach > {
  static const char* value()
  {
    return "wam_srvs/Teach";
  }

  static const char* value(const ::wam_srvs::Teach&) { return value(); }
};


// service_traits::MD5Sum< ::wam_srvs::TeachRequest> should match 
// service_traits::MD5Sum< ::wam_srvs::Teach > 
template<>
struct MD5Sum< ::wam_srvs::TeachRequest>
{
  static const char* value()
  {
    return MD5Sum< ::wam_srvs::Teach >::value();
  }
  static const char* value(const ::wam_srvs::TeachRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_srvs::TeachRequest> should match 
// service_traits::DataType< ::wam_srvs::Teach > 
template<>
struct DataType< ::wam_srvs::TeachRequest>
{
  static const char* value()
  {
    return DataType< ::wam_srvs::Teach >::value();
  }
  static const char* value(const ::wam_srvs::TeachRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::wam_srvs::TeachResponse> should match 
// service_traits::MD5Sum< ::wam_srvs::Teach > 
template<>
struct MD5Sum< ::wam_srvs::TeachResponse>
{
  static const char* value()
  {
    return MD5Sum< ::wam_srvs::Teach >::value();
  }
  static const char* value(const ::wam_srvs::TeachResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_srvs::TeachResponse> should match 
// service_traits::DataType< ::wam_srvs::Teach > 
template<>
struct DataType< ::wam_srvs::TeachResponse>
{
  static const char* value()
  {
    return DataType< ::wam_srvs::Teach >::value();
  }
  static const char* value(const ::wam_srvs::TeachResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WAM_SRVS_MESSAGE_TEACH_H
