// Generated by gencpp from file wam_srvs/TP_PIDRequest.msg
// DO NOT EDIT!


#ifndef WAM_SRVS_MESSAGE_TP_PIDREQUEST_H
#define WAM_SRVS_MESSAGE_TP_PIDREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace wam_srvs
{
template <class ContainerAllocator>
struct TP_PIDRequest_
{
  typedef TP_PIDRequest_<ContainerAllocator> Type;

  TP_PIDRequest_()
    : kp(0.0)
    , kd(0.0)
    , ki(0.0)  {
    }
  TP_PIDRequest_(const ContainerAllocator& _alloc)
    : kp(0.0)
    , kd(0.0)
    , ki(0.0)  {
  (void)_alloc;
    }



   typedef float _kp_type;
  _kp_type kp;

   typedef float _kd_type;
  _kd_type kd;

   typedef float _ki_type;
  _ki_type ki;





  typedef boost::shared_ptr< ::wam_srvs::TP_PIDRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wam_srvs::TP_PIDRequest_<ContainerAllocator> const> ConstPtr;

}; // struct TP_PIDRequest_

typedef ::wam_srvs::TP_PIDRequest_<std::allocator<void> > TP_PIDRequest;

typedef boost::shared_ptr< ::wam_srvs::TP_PIDRequest > TP_PIDRequestPtr;
typedef boost::shared_ptr< ::wam_srvs::TP_PIDRequest const> TP_PIDRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::wam_srvs::TP_PIDRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::wam_srvs::TP_PIDRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace wam_srvs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::wam_srvs::TP_PIDRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wam_srvs::TP_PIDRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wam_srvs::TP_PIDRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wam_srvs::TP_PIDRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wam_srvs::TP_PIDRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wam_srvs::TP_PIDRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::wam_srvs::TP_PIDRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8dfae169c05c8647d6140e2a6c279a75";
  }

  static const char* value(const ::wam_srvs::TP_PIDRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8dfae169c05c8647ULL;
  static const uint64_t static_value2 = 0xd6140e2a6c279a75ULL;
};

template<class ContainerAllocator>
struct DataType< ::wam_srvs::TP_PIDRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "wam_srvs/TP_PIDRequest";
  }

  static const char* value(const ::wam_srvs::TP_PIDRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::wam_srvs::TP_PIDRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 kp\n"
"float32 kd\n"
"float32 ki\n"
;
  }

  static const char* value(const ::wam_srvs::TP_PIDRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::wam_srvs::TP_PIDRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.kp);
      stream.next(m.kd);
      stream.next(m.ki);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TP_PIDRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::wam_srvs::TP_PIDRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::wam_srvs::TP_PIDRequest_<ContainerAllocator>& v)
  {
    s << indent << "kp: ";
    Printer<float>::stream(s, indent + "  ", v.kp);
    s << indent << "kd: ";
    Printer<float>::stream(s, indent + "  ", v.kd);
    s << indent << "ki: ";
    Printer<float>::stream(s, indent + "  ", v.ki);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WAM_SRVS_MESSAGE_TP_PIDREQUEST_H
