# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from wam_msgs/RTOrtn.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class RTOrtn(genpy.Message):
  _md5sum = "2e3f1019db9e6ee5ee0fb74a74917cbb"
  _type = "wam_msgs/RTOrtn"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float32[4] orientation
float32[3] kp
float32[3] kd
bool change_gains
"""
  __slots__ = ['orientation','kp','kd','change_gains']
  _slot_types = ['float32[4]','float32[3]','float32[3]','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       orientation,kp,kd,change_gains

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(RTOrtn, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.orientation is None:
        self.orientation = [0.] * 4
      if self.kp is None:
        self.kp = [0.] * 3
      if self.kd is None:
        self.kd = [0.] * 3
      if self.change_gains is None:
        self.change_gains = False
    else:
      self.orientation = [0.] * 4
      self.kp = [0.] * 3
      self.kd = [0.] * 3
      self.change_gains = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      buff.write(_get_struct_4f().pack(*self.orientation))
      buff.write(_get_struct_3f().pack(*self.kp))
      buff.write(_get_struct_3f().pack(*self.kd))
      buff.write(_get_struct_B().pack(self.change_gains))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      start = end
      end += 16
      self.orientation = _get_struct_4f().unpack(str[start:end])
      start = end
      end += 12
      self.kp = _get_struct_3f().unpack(str[start:end])
      start = end
      end += 12
      self.kd = _get_struct_3f().unpack(str[start:end])
      start = end
      end += 1
      (self.change_gains,) = _get_struct_B().unpack(str[start:end])
      self.change_gains = bool(self.change_gains)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      buff.write(self.orientation.tostring())
      buff.write(self.kp.tostring())
      buff.write(self.kd.tostring())
      buff.write(_get_struct_B().pack(self.change_gains))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      start = end
      end += 16
      self.orientation = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=4)
      start = end
      end += 12
      self.kp = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=3)
      start = end
      end += 12
      self.kd = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=3)
      start = end
      end += 1
      (self.change_gains,) = _get_struct_B().unpack(str[start:end])
      self.change_gains = bool(self.change_gains)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4f = None
def _get_struct_4f():
    global _struct_4f
    if _struct_4f is None:
        _struct_4f = struct.Struct("<4f")
    return _struct_4f
_struct_B = None
def _get_struct_B():
    global _struct_B
    if _struct_B is None:
        _struct_B = struct.Struct("<B")
    return _struct_B
_struct_3f = None
def _get_struct_3f():
    global _struct_3f
    if _struct_3f is None:
        _struct_3f = struct.Struct("<3f")
    return _struct_3f
