# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from wam_msgs/RTVelocity.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class RTVelocity(genpy.Message):
  _md5sum = "6fd73d4c205ad728e90044131e5d954b"
  _type = "wam_msgs/RTVelocity"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float32[3] v_direction
float32 v_magnitude
float32 kp
bool change_gains
"""
  __slots__ = ['v_direction','v_magnitude','kp','change_gains']
  _slot_types = ['float32[3]','float32','float32','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       v_direction,v_magnitude,kp,change_gains

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(RTVelocity, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.v_direction is None:
        self.v_direction = [0.] * 3
      if self.v_magnitude is None:
        self.v_magnitude = 0.
      if self.kp is None:
        self.kp = 0.
      if self.change_gains is None:
        self.change_gains = False
    else:
      self.v_direction = [0.] * 3
      self.v_magnitude = 0.
      self.kp = 0.
      self.change_gains = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      buff.write(_get_struct_3f().pack(*self.v_direction))
      _x = self
      buff.write(_get_struct_2fB().pack(_x.v_magnitude, _x.kp, _x.change_gains))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      start = end
      end += 12
      self.v_direction = _get_struct_3f().unpack(str[start:end])
      _x = self
      start = end
      end += 9
      (_x.v_magnitude, _x.kp, _x.change_gains,) = _get_struct_2fB().unpack(str[start:end])
      self.change_gains = bool(self.change_gains)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      buff.write(self.v_direction.tostring())
      _x = self
      buff.write(_get_struct_2fB().pack(_x.v_magnitude, _x.kp, _x.change_gains))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      start = end
      end += 12
      self.v_direction = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=3)
      _x = self
      start = end
      end += 9
      (_x.v_magnitude, _x.kp, _x.change_gains,) = _get_struct_2fB().unpack(str[start:end])
      self.change_gains = bool(self.change_gains)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2fB = None
def _get_struct_2fB():
    global _struct_2fB
    if _struct_2fB is None:
        _struct_2fB = struct.Struct("<2fB")
    return _struct_2fB
_struct_3f = None
def _get_struct_3f():
    global _struct_3f
    if _struct_3f is None:
        _struct_3f = struct.Struct("<3f")
    return _struct_3f
