// Generated by gencpp from file wam_msgs/RTVelocity.msg
// DO NOT EDIT!


#ifndef WAM_MSGS_MESSAGE_RTVELOCITY_H
#define WAM_MSGS_MESSAGE_RTVELOCITY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace wam_msgs
{
template <class ContainerAllocator>
struct RTVelocity_
{
  typedef RTVelocity_<ContainerAllocator> Type;

  RTVelocity_()
    : v_direction()
    , v_magnitude(0.0)
    , kp(0.0)
    , change_gains(false)  {
      v_direction.assign(0.0);
  }
  RTVelocity_(const ContainerAllocator& _alloc)
    : v_direction()
    , v_magnitude(0.0)
    , kp(0.0)
    , change_gains(false)  {
  (void)_alloc;
      v_direction.assign(0.0);
  }



   typedef boost::array<float, 3>  _v_direction_type;
  _v_direction_type v_direction;

   typedef float _v_magnitude_type;
  _v_magnitude_type v_magnitude;

   typedef float _kp_type;
  _kp_type kp;

   typedef uint8_t _change_gains_type;
  _change_gains_type change_gains;





  typedef boost::shared_ptr< ::wam_msgs::RTVelocity_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wam_msgs::RTVelocity_<ContainerAllocator> const> ConstPtr;

}; // struct RTVelocity_

typedef ::wam_msgs::RTVelocity_<std::allocator<void> > RTVelocity;

typedef boost::shared_ptr< ::wam_msgs::RTVelocity > RTVelocityPtr;
typedef boost::shared_ptr< ::wam_msgs::RTVelocity const> RTVelocityConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::wam_msgs::RTVelocity_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::wam_msgs::RTVelocity_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace wam_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'wam_msgs': ['/home/dhruv/gitwkspc/RobotArm/wam_dir/src/wam_common/wam_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::wam_msgs::RTVelocity_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wam_msgs::RTVelocity_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wam_msgs::RTVelocity_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wam_msgs::RTVelocity_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wam_msgs::RTVelocity_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wam_msgs::RTVelocity_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::wam_msgs::RTVelocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6fd73d4c205ad728e90044131e5d954b";
  }

  static const char* value(const ::wam_msgs::RTVelocity_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6fd73d4c205ad728ULL;
  static const uint64_t static_value2 = 0xe90044131e5d954bULL;
};

template<class ContainerAllocator>
struct DataType< ::wam_msgs::RTVelocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "wam_msgs/RTVelocity";
  }

  static const char* value(const ::wam_msgs::RTVelocity_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::wam_msgs::RTVelocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[3] v_direction\n"
"float32 v_magnitude\n"
"float32 kp\n"
"bool change_gains\n"
;
  }

  static const char* value(const ::wam_msgs::RTVelocity_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::wam_msgs::RTVelocity_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.v_direction);
      stream.next(m.v_magnitude);
      stream.next(m.kp);
      stream.next(m.change_gains);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RTVelocity_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::wam_msgs::RTVelocity_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::wam_msgs::RTVelocity_<ContainerAllocator>& v)
  {
    s << indent << "v_direction[]" << std::endl;
    for (size_t i = 0; i < v.v_direction.size(); ++i)
    {
      s << indent << "  v_direction[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.v_direction[i]);
    }
    s << indent << "v_magnitude: ";
    Printer<float>::stream(s, indent + "  ", v.v_magnitude);
    s << indent << "kp: ";
    Printer<float>::stream(s, indent + "  ", v.kp);
    s << indent << "change_gains: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.change_gains);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WAM_MSGS_MESSAGE_RTVELOCITY_H
